module.exports = {
    darkMode: "class",
    theme: {
        container: {
            center: true,          // auto margin
            padding: '1rem',       // optional inner padding
            maxWidth: { '2xl': '1280px' },

        },
        extend: {
            colors: {
                "inverse-primary": "#84d98e",
                "secondary": "#216296",
                "on-secondary": "#ffffff",
                "earth-copper": "#B87333",
                "on-background": "#1b1b1b",
                "on-secondary-container": "#005083",
                "primary-fixed-dim": "#84d98e",
                "text-muted": "#757575",
                "surface-container-low": "#f6f3f2",
                "tertiary-container": "#5d5d59",
                "surface-dim": "#dcd9d9",
                "on-primary-fixed": "#002108",
                "background": "#fcf9f8",
                "on-primary": "#ffffff",
                "inverse-on-surface": "#f3f0ef",
                "surface-variant": "#e5e2e1",
                "on-error": "#ffffff",
                "secondary-fixed": "#d0e4ff",
                "on-tertiary": "#ffffff",
                "inverse-surface": "#303030",
                "surface-tint": "#116d2f",
                "surface-container-highest": "#e5e2e1",
                "secondary-container": "#8bc3fd",
                "error-container": "#ffdad6",
                "outline": "#707a6e",
                "text-secondary": "#555555",
                "surface-bright": "#fcf9f8",
                "border-neutral": "#E3DDD2",
                "primary-container": "#0d6b2d",
                "on-tertiary-container": "#d8d6d1",
                "tertiary-fixed-dim": "#c8c6c2",
                "on-tertiary-fixed-variant": "#474744",
                "harvest-gold": "#D8A428",
                "surface-container-high": "#eae7e7",
                "tertiary-fixed": "#e4e2dd",
                "on-secondary-fixed-variant": "#004a79",
                "accent-blue": "#00A1DF",
                "on-primary-fixed-variant": "#00531f",
                "outline-variant": "#bfcabb",
                "on-surface-variant": "#3f493f",
                "terracotta": "#A44A3F",
                "surface": "#fcf9f8",
                "on-error-container": "#93000a",
                "on-primary-container": "#92e99c",
                "on-secondary-fixed": "#001d34",
                "secondary-fixed-dim": "#9acbff",
                "tertiary": "#454542",
                "primary-fixed": "#9ff6a8",
                "on-tertiary-fixed": "#1b1c19",
                "warm-beige": "#F3EFE7",
                "on-surface": "#1b1b1b",
                "surface-container": "#f0eded",
                "primary": "#00511e",
                "error": "#ba1a1a",
                "surface-container-lowest": "#ffffff"
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px"
            },
            spacing: {
                "section-desktop": "140px",
                "stack-lg": "48px",
                "section-mobile": "80px",
                "gutter": "32px",
                "stack-sm": "12px",
                "stack-md": "24px",
                "container-max": "95%",
            },
            fontFamily: {
                "statistic-num": ["var(--font-epilogue)", "sans-serif"],
                "display-lg": ["var(--font-epilogue)", "sans-serif"],
                "label-caps": ["var(--font-manrope)", "sans-serif"],
                "headline-md": ["var(--font-epilogue)", "sans-serif"],
                "display-lg-mobile": ["var(--font-epilogue)", "sans-serif"],
                "headline-lg": ["var(--font-epilogue)", "sans-serif"],
                "body-lg": ["var(--font-manrope)", "sans-serif"],
                "body-md": ["var(--font-manrope)", "sans-serif"],
            },
            fontSize: {
                "statistic-num": ["14vh", { lineHeight: "1.2em", fontWeight: "700" }],
                "display-lg": ["80px", { lineHeight: "90px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "label-caps": ["2vh", { lineHeight: "1.4em", letterSpacing: "0.1em", fontWeight: "700" }],
                "headline-xl": ["12vw", { lineHeight: "1em", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-lg": ["5.5vw", { lineHeight: "1.2em", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-md": ["3vw", { lineHeight: "1.2em", fontWeight: "700" }],
                "headline-sm": ["2vw", { lineHeight: "1.2em", fontWeight: "600" }],
                "display-lg-mobile": ["48px", { lineHeight: "1.2em", letterSpacing: "-0.01em", fontWeight: "700" }],
                "body-lg": ["1.2vw", { lineHeight: "1.2em", fontWeight: "400" }],
                "body-md": ["1.1vw", { lineHeight: "1.2em", fontWeight: "400" }],
                "body-sm": ["0.7vw", { lineHeight: "1.2em", fontWeight: "400" }]
            },
            animation: {
                marquee: "marquee var(--marquee-duration, 30s) linear infinite",
                "marquee-reverse": "marquee-reverse var(--marquee-duration, 30s) linear infinite",
                "marquee-vertical-up": "marquee-vertical-up var(--marquee-duration, 40s) linear infinite",
                "marquee-vertical-down": "marquee-vertical-down var(--marquee-duration, 40s) linear infinite",
            },
            keyframes: {
                marquee: {
                    "0%": { transform: "translateX(0%)" },
                    "100%": { transform: "translateX(-100%)" },
                },
                "marquee-reverse": {
                    "0%": { transform: "translateX(-100%)" },
                    "100%": { transform: "translateX(0%)" },
                },
                "marquee-vertical-up": {
                    "0%": { transform: "translateY(0%)" },
                    "100%": { transform: "translateY(-50%)" },
                },
                "marquee-vertical-down": {
                    "0%": { transform: "translateY(-50%)" },
                    "100%": { transform: "translateY(0%)" },
                },
            },
        }
    }
};