# Generated by Django 5.2.5 on 2026-07-08 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to='clients/logos/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
    ]
