# Generated by Django 5.2.5 on 2026-08-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/sections/'),
        ),
        migrations.AddField(
            model_name='client',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/projects/'),
        ),
    ]
