# Generated by Django 5.2.5 on 2026-07-08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=150)),
                ("value", models.PositiveIntegerField()),
                ("suffix", models.CharField(blank=True, max_length=10)),
                ("display_order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ("display_order",),
            },
        ),
    ]
